services:
  wordpress:
    build: .
    entrypoint: ["/usr/local/bin/custom-entrypoint.sh"]
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      MAILCHIMP_API_KEY: your-mailchimp-api-key-here  # <-- Set your Mailchimp API key here
    volumes:
      - ./wp-content/themes/ctf-landing-pages:/var/www/html/wp-content/themes/ctf-landing-pages
      - ./wp-content/plugins/wp-petition-mailchimp:/var/www/html/wp-content/plugins/wp-petition-mailchimp
    depends_on:
      - db
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
